### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by andreiadamian** [kallura/eurovision-votes#1]
`gradle build --info -- stacktrace`

Failed tests:
```
org.eurovision.EurovisionTest > mainPositiveFlow STANDARD_ERROR
    ERR: input.txt (No such file or directory)
    java.io.FileNotFoundException: input.txt (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at org.eurovision.command.LoadCommand._run(LoadCommand.java:42)
        at org.eurovision.command.LoadCommand.run(LoadCommand.java:37)
```

**Comment by kallura** [comment]
fixed
